CREATE TABLE EMPLOYEE(
    FNAME VARCHAR(20),
    MINIT CHAR(1),
    LNAME VARCHAR(20),
    SSN CHAR(9),
    BDATE DATE,
    ADDRESS VARCHAR(30),
    SEX CHAR(1),
    SALARY DECIMAL(10, 2),
    SUPERSSN CHAR(9),
    DNO INT(1)
);

CREATE TABLE DEPARTMENT(
    DNAME VARCHAR(20),
    DNUMBER INT(1),
    MGR_SSN CHAR(9),
    MGR_START_DATE DATE
);

CREATE TABLE DEPT_LOCATIONS(
    DNUMBER INT(1),
    DLOCATION VARCHAR(20)
);

CREATE TABLE PROJECT(
    PNAME VARCHAR(20),
    PNUMBER INT(1),
    PLOCATION VARCHAR(20),
    DNUM INT(1)
);

CREATE TABLE WORKS_ON(
    ESSN INT(9),
    PNO INT(1),
    HOURS DECIMAL(3, 1)
);

CREATE TABLE DEPENDENT(
    ESSN INT(9),
    DEPENDENT_NAME VARCHAR(20),
    SEX CHAR(1),
    BDATE DATE,
    RELATIONSHIP VARCHAR(20)
);

