create database test_1;
use test_1;

CREATE TABLE STUDENT(
    NAME VARCHAR(20),
    STUDENT_NUMBER INT(4),
    CLASS INT(2),
    MAJOR CHAR(4)
);

CREATE TABLE COURSE(
    COURSE_NAME VARCHAR(50),
    COURSE_NUMBER VARCHAR(50),
    CREDIT_HOURS INT(4),
    DEPARTMENT CHAR(4)
);


CREATE TABLE SECTION(
    SECTION_IDENTIFIER INT(4),
    COURSE_NUMBER VARCHAR(50),
    SEMESTER CHAR(50),
    YEAR INT(4),
    INSTRUCTOR CHAR(50)
);


CREATE TABLE GRADE_REPORT(
    STUDENT_NUMBER INT(4),
    SECTION_IDENTIFIER INT(4),
    GRADE CHAR(2)
);

CREATE TABLE PREREQUISITE(
    COURSE_NUMBER VARCHAR(50),
    PREREQUISITE_NUMBER VARCHAR(50)
);


--INSERT DATA TO THE ALREADY CREATED TABLES

INSERT INTO GRADE_REPORT(STUDENT_NUMBER, SECTION_IDENTIFIER, GRADE)VALUES
    (17,112,"B"),
    (17,119,"C"),
    (8,85,"A"),
    (8,92,"A"),
    (8,102,"B"),
    (8,135,"A");

