-- Create SAILORS table
CREATE TABLE SAILORS (
    SID VARCHAR(10) PRIMARY KEY,
    SNAME VARCHAR(50) NOT NULL,
    RATINGS INT,
    AGE INT
);

-- Create BOATS table
CREATE TABLE BOATS (
    BID VARCHAR(10) PRIMARY KEY,
    BNAME VARCHAR(50) NOT NULL,
    COLOUR VARCHAR(20)
);  

-- Create RESERVES table
CREATE TABLE RESERVES (
    SID VARCHAR(10),
    BID VARCHAR(10),
    DAY DATE,
    PRIMARY KEY (SID, BID, DAY)
);

-- Add Foreign Key to RESERVES table
ALTER TABLE RESERVES
ADD CONSTRAINT FK_RESERVES_SAILORS 
FOREIGN KEY (SID) REFERENCES SAILORS(SID);

ALTER TABLE RESERVES
ADD CONSTRAINT FK_RESERVES_BOATS 
FOREIGN KEY (BID) REFERENCES BOATS(BID);