CREATE DATABASE SHIP_DB-T1;

USE SHIP_DB-T1;
#CREATE THE SAILORS TABLE 
CREATE TABLE SAILORS(
    SID VARCHAR(10) PRIMARY KEY,
    SNAME VARCHAR(50) NOT NULL,
    RATINGS INT,
    AGE INT
);
#CREATE THE BOATS TABLE
CREATE TABLE BOATS(
    BID VARCHAR(10) PRIMARY KEY,
    BNAME VARCHAR(50) NOT NULL,
    COLOUR VARCHAR(20)
);
#CREATE THE RESERVES TABLE
CREATE TABLE RESERVES(
    SID VARCHAR(10),
    BID VARCHAR(10),
    DAY DATE,
    PRIMARY KEY (SID,BID,DAY)
);
#ADD THE FOREIGN KEYS AFTER WE HAVE CREATED THE TABLE BY USING ALTER TABLE
ALTER TABLE RESERVES
ADD CONSTRAINT FK_RESERVES_SAILORS
FOREIGN KEY (SID) REFERENCES SAILORS(SID);

#ADD THE FOREIGN KEYS AFTER WE HAVE CREATED THE TABLE BY USING ALTER TABLE
ALTER TABLE RESERVES
ADD CONSTRAINT FK_RESERVES_BOATS
FOREIGN KEY (BID) REFERENCES BOATS(BID);






-- to insert data to the create tables;

INSERT INTO SAILORS(SID,SNAME,RATINGS,AGE)VALUES
    ('S21','HARI',4,21),
    ('S22','RAKESH',5,24),
    ('S23','VEEERU',4,45),
    ('S24','RAHUL',3,33),
    ('S25','RAMU',3,30);


INSERT INTO BOATS (BID, BNAME, COLOR) VALUES
    ('B101', 'B1', 'WHITE'),
    ('B102', 'B2', 'RED'),
    ('B103', 'B3', 'WHITE'),
    ('B104', 'B4', 'BLUE');

INSERT INTO RESERVES (SID, BID, DAY) VALUES
    ('S21', 'B101', '2024-12-03'),
    ('S24', 'B103', '2024-12-05'),
    ('S23', 'B104', '2024-12-03'),
    ('S21', 'B101', '2024-12-10');


SELECT S.SNAME, R.SID
FROM SAILORS S 
JOIN RESERVES R ON S.SID = R.SID;


SELECT S.SNAME, B.COLOR, R.DAY
FROM SAILORS S
JOIN RESERVES R AND BOATS B ON S.SID = R.SID AND B.BID = R.BID;


SELECT B.BNAME , B.COLOR
FROM BOATS B;

SELECT S.SNAME, R.BID
FROM SAILORS S
JOIN RESERVES R ON S.SID = R.SID;

#List the boat names along with the names of sailors who reserved them. 

SELECT B.BNAME , S.SNAME
FROM BOATS B
JOIN RESERVES R ON B.BID = R.BID
JOIN SAILORS S ON R.SID = S.SID;


SELECT S.SNAME , B.COLOR, R.DAY
FROM SAILORS S
JOIN RESERVES R ON S.SID = R.SID
JOIN BOATS B ON R.BID = B.BID;

SELECT S.SNAME , S.RATINGS, B.BNAME
FROM SAILORS S
JOIN RESERVES R ON S.SID = R.SID
JOIN BOATS B ON R.BID = B.BID;
#Find the sailors who reserved on "2024-12-03"

SELECT S.SNAME
FROM SAILORS S
JOIN RESERVES R ON S.SID = R.SID
WHERE R.DAY = "2024-12-03";


SELECT S.SNAME
FROM SAILORS S
JOIN RESERVES R ON S.SID = R.SID
JOIN BOATS B ON R.BID = B.BID 
WHERE B.COLOR = "WHITE";

SELECT S.SNAME,S.RATINGS,B.COLOR
FROM SAILORS S
JOIN RESERVES R ON S.SID = R.SID
JOIN BOATS B ON R.BID = B.BID
WHERE R.DAY = "2024-12-03";


SELECT B.BA

SELECT B.BNAME, COUNT(R.BID) AS TOTAL_RESERVATIONS 
FROM BOATS B 
LEFT JOIN RESERVES R ON B.BID = R.BID 
GROUP BY B.BID;  

Find sailors older than 30 who reserved red boats.

SELECT S.SNAME
FROM SAILORS S
JOIN RESERVES R ON S.SID = R.SID
JOIN BOATS B ON R.BID = B.BID
WHERE S.AGE > 30 AND B.COLOR = "BLUE";


SELECT S.SNAME ,S.RATINGS, COUNT(S.RATINGS) AS RATINGS_N0
FROM SAILORS S
GROUP BY S.RATINGS;